import React from "react";
import { Metadata } from "next";
import { Inter, Roboto_Mono } from "@next/font/google";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Daniel's Portfolio",
  description: "Generated by dnx devs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${inter.variable} ${robotoMono.variable}`}>{children}</div>
  );
}
